### ISSUE TITLE
yek.yaml doesn't ignore itself

### ISSUE THREAD

**Issue by deadcoder0904** [bodo-run/yek#129]
I created `yek.yaml` in my own project & I did `yek . | pbcopy`

I saw the output even included `yek.yaml`. I don't think its useful at all for the LLM so think it should be ignored by default.

Currently, I have to ignore it in `.yaml`:

```yaml
# Add patterns to ignore (in addition to .gitignore)
ignore_patterns:
  - dist/**
  - bun.lock
  - yek.yaml

# Configure Git-based priority boost (optional)
git_boost_max: 50 # Maximum score boost based on Git history (default: 100)

# Define priority rules for processing order
# Higher scores are processed first
priority_rules:
  - score: 100
    pattern: "^src/main/"
  - score: 90
    pattern: "^src/renderer"
  - score: 80
    pattern: "^docs/"

# Define output template.
# FILE_PATH and FILE_CONTENT are expected to be present in the template.
output_template: "{{{FILE_PATH}}}\n\nFILE_CONTENT"
```
