### ISSUE TITLE
yek | pbcopy polluted with "Skipping ignored file:"

### ISSUE THREAD

**Issue by do-me** [bodo-run/yek#83]
Hey, I just upgraded to v16 and noted that now my `yek | pbcopy` command includes thousands of lines for ignored files like this: 

```
[2m2025-02-05T08:39:57.244681Z[0m [34mDEBUG[0m Skipping ignored file: vendor/node_modules/lru-cache/dist/commonjs/package.json
[2m2025-02-05T08:39:57.244686Z[0m [34mDEBUG[0m Skipping ignored file: vendor/node_modules/lru-cache/dist/commonjs/index.js
...
```

I'm working on a svn (legacy) repo and also get this line in the beginning, maybe that's relevant? 

`Not a Git repository or unable to open: "."`

This is my yek.yaml: 

```yaml
# Yek configuration file for creating LLM-ready text dumps of code https://github.com/bodo-run/yek

# Add patterns to ignore (in addition to .gitignore)
ignore_patterns:
  - "ai-promots/**"
  - "__generated__/**"
  - "node_modules/**"
  - "vendor/node_modules/**"
  - "build/**"
  - "dist/**"
  - "tmp/**"

# Configure Git-based priority boost (optional)
git_boost_max: 50 # Maximum score boost based on Git history (default: 100)

# Define priority rules for processing order
# Higher scores are processed first
priority_rules:
  - score: 100
    pattern: "^app/"

# Add additional binary file extensions to ignore
# These extend the built-in list (.jpg, .png, .exe, etc.)
binary_extensions:
  - ".blend" # Blender files
  - ".fbx" # 3D model files
  - ".max" # 3ds Max files
  - ".psd" # Photoshop files

# Define output directory
output_dir: /tmp/yek

# Define output template.
# FILE_PATH and FILE_CONTENT are expected to be present in the template.
output_template: "{{{FILE_PATH}}}\n\nFILE_CONTENT"
```

I guess the default behavior should be to not include it. 

Currently I'm using the dirty workaround: `yek 2>&1 | grep -v "DEBUG" | pbcopy` that gets the job done.
